### PR TITLE
PR for Dashboard client, Redux complete except for delete part

### PR DESCRIPTION
**Pull request by azztt**
Almost done, logout remaining, api links to be corrected after testing soon.

### CODE REVIEW

**Comment by ankurshaswat** [comment]
Fix merge errors in Dockerfile and docker-compose.yml

**Comment by ankurshaswat** [comment]
Lot of errors on starting
Please ensure `npm start` is working

**Comment by azztt** [comment]
> Lot of errors on starting
> Please ensure `npm start` is working

That was because of null initial state of users, projects, events, resources in store. Now configured for local use with just dummy data in initial state.

**Comment by ankurshaswat** [comment]
There was a syntax error
Then there was an error of conditional react hook

Fixed both?

**Pull request merged**
